on:
  push:
  workflow_dispatch:

name: OSX and Conda

env:
  GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
  R_REMOTES_NO_ERRORS_FROM_WARNINGS: true

jobs:
  test-pkg:
    runs-on: macOS-14
    name: testing conda

    steps:

      - uses: actions/checkout@v4
          
      - uses: conda-incubator/setup-miniconda@v3
        with:
          use-mamba: true
          miniconda-version: "latest"
          channels: conda-forge,defaults,bioconda
          channel-priority: true
          activate-environment: foo
          architecture: arm64
      
      - name: Bash
        shell: bash -el {0}
        run: |
          uname -a
          conda install -c r r-biocmanager bioconductor-rhdf5lib
          echo $PATH
          conda list

      - name: R
        shell: bash -el {0}
        run: |
          R -e '.libPaths()' -e 'installed.packages()[,1:2]' -e 'sessionInfo()'
          R -e 'library(Rhdf5lib)'

      - name: Install Rhdf5lib from source
        shell: bash -el {0}
        run: |
          R -e 'BiocManager::install("Rhdf5lib", lib = tempdir())'
          
