on:
  push:
  workflow_dispatch:

name: OSX and Conda

env:
  GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
  R_REMOTES_NO_ERRORS_FROM_WARNINGS: true

jobs:
  test-pkg:
    runs-on: macOS-14
    name: testing conda

    steps:

      - uses: actions/checkout@v4
          
      - uses: conda-incubator/setup-miniconda@v3
        with:
          use-mamba: true
          miniconda-version: "latest"
          channels: conda-forge,defaults,bioconda
          channel-priority: true
          activate-environment: foo
          architecture: arm64
      
      - name: System details
        shell: bash -el {0}
        run: |
          echo ${host_alias}
          echo ${build_alias}
          
      - name: Testing scripts
        shell: bash -el {0}
        run: |
          wget -O config.sub https://git.savannah.gnu.org/cgit/config.git/plain/config.sub 
          wget -O config.guess https://git.savannah.gnu.org/cgit/config.git/plain/config.guess 
          bash ./config.guess
          bash ./config.sub $(bash ./config.guess)
        working-directory: ${{ runner.temp }}  
          
      - name: Bash
        shell: bash -el {0}
        run: |
          conda install -c r r-biocmanager

      - name: Install Rhdf5lib from source
        shell: bash -el {0}
        run: |
          R -e 'BiocManager::install("Rhdf5lib", lib = tempdir())'
          
      - name: Install Rhdf5lib from source
        shell: bash -el {0}
        run: |
          unset host_alias
          unset build_alias
          R -e 'BiocManager::install("Rhdf5lib", lib = tempdir())'
          
