on:
  push:
  pull_request:
    branches:
      - master

name: R-CMD-check

env:
  GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
  R_REMOTES_NO_ERRORS_FROM_WARNINGS: true

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }} (${{ matrix.config.bioc-version }})

    strategy:
      fail-fast: false
      matrix:
        config:
        - { os: windows-2022, bioc-version: 'devel'}
        - { os: macOS-latest, bioc-version: 'devel'}
        - { os: ubuntu-20.04, bioc-version: 'devel', system-libs: 'libcurl4-gnutls-dev libaec-dev'}
        - { os: ubuntu-22.04, bioc-version: 'devel', system-libs: 'libcurl4-openssl-dev'}

    steps:
      - name: Configure git
        run: |
          git config --global core.autocrlf false

      - name: Install Linux system libraries
        if: ${{ runner.os == 'Linux' }}
        run: |
          sudo apt-get update && sudo apt-get install ${{ matrix.config.system-libs }}
          
      - name: Install Mac system libraries
        if: ${{ matrix.config.os == 'macOS-latest' }}
        run: |
          sudo Rscript -e 'source("https://mac.R-project.org/bin/install.R")' -e 'install.libs("openssl")'
        shell: bash
        
      - uses: actions/checkout@v3
          
      - name: Setup R and Bioconductor
        uses: grimbough/bioc-actions/setup-bioc@v1
        with:
          bioc-version: ${{ matrix.config.bioc-version }}
          bioc-mirror: https://ftp.gwdg.de/pub/misc/bioconductor
          
      # - name: Create Makevars
      #   if: ${{ matrix.config.os == 'macOS-latest' }}
      #   run: |
      #     mkdir $HOME/.R
      #     echo 'LDFLAGS="-L/usr/local/opt/openssl@1.1/lib"' > $HOME/.R/Makevars
      #     echo 'CPPFLAGS="-I/usr/local/opt/openssl@1.1/include"' >> $HOME/.R/Makevars

      - uses: r-lib/actions/setup-pandoc@v2

      - name: Install dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
        ## install BiocCheck here so it is cached
          extra-packages: |
            bioc::BiocCheck
        
      - name: Bioc - Build, Install, Check
        id: build-install-check
        uses: grimbough/bioc-actions/build-install-check@v1
        
      - name: Run BiocCheck
        uses: grimbough/bioc-actions/run-BiocCheck@v1
        with:
          error-on: 'never'
          arguments: '--no-check-bioc-help' 
      
      - name: Session info
        run: |
          sessionInfo()
        shell: Rscript {0}
        
      - name: Check libhdf5 status
        run: |
          ls -l ${R_LIBS_USER}/Rhdf5lib/lib
          nm ${R_LIBS_USER}/Rhdf5lib/lib/libhdf5.a | grep EVP_sha256
        shell: bash
        
      - name: Upload check results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.config.os }}-results
          path: ${{ steps.build-install-check.outputs.check-dir }}
          
      - name: Upload check results
        if: ${{ failure() }}
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.config.os }}-${{ matrix.config.r }}-hdf5_config.log
          path: check/*.Rcheck/00_pkg_src/Rhdf5lib/src/hdf5/config.log
          
      ## upload source and binary packages
      - name: Upload check output
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os }}-bioc-${{ matrix.bioc-version}}-pkgs
          path: |
            ${{ steps.build-install-check.outputs.source-tarball }}
            ${{ steps.build-install-check.outputs.package-binary }}
            
