on:
  push:
    branches-ignore:
      - mac-conda
  pull_request:
    branches:
      - devel

name: R-CMD-check

env:
  GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
  R_REMOTES_NO_ERRORS_FROM_WARNINGS: true

jobs:
  R-CMD-check:
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }} (${{ matrix.config.bioc-version }})

    strategy:
      fail-fast: false
      matrix:
        config:
        - { os: windows-2025,     bioc-version: 'devel', Ncpus: 4}
        - { os: windows-11-arm,   bioc-version: 'devel', Ncpus: 4}
        - { os: macOS-15-intel,   bioc-version: 'devel', Ncpus: 4}
        - { os: macOS-15,         bioc-version: 'devel', Ncpus: 3}
        - { os: ubuntu-24.04,     bioc-version: 'devel', Ncpus: 4, system-libs: 'libcurl4-gnutls-dev libaec-dev'}
        - { os: ubuntu-24.04,     bioc-version: 'devel', Ncpus: 4, system-libs: 'libcurl4-openssl-dev'}
        - { os: ubuntu-24.04-arm, bioc-version: 'devel', Ncpus: 4}

    steps:
      - name: Install Linux system libraries
        if: ${{ runner.os == 'Linux' }}
        run: |
          sudo apt-get update && sudo apt-get install ${{ matrix.config.system-libs }}
        
      - uses: actions/checkout@v4
          
      - name: Setup R and Bioconductor
        uses: grimbough/bioc-actions/setup-bioc@v1
        with:
          bioc-version: ${{ matrix.config.bioc-version }}
          bioc-mirror: https://ftp.gwdg.de/pub/misc/bioconductor
          Ncpus: ${{ matrix.config.Ncpus }}
          
      - uses: r-lib/actions/setup-pandoc@v2

      - name: Install dependencies
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
        ## install BiocCheck here so it is cached
          extra-packages: |
            bioc::BiocCheck
        
      - name: Bioc - Build, Install, Check
        id: build-install-check
        uses: grimbough/bioc-actions/build-install-check@v1
        
      - name: Run BiocCheck
        uses: grimbough/bioc-actions/run-BiocCheck@v1
        with:
          error-on: 'never'
          arguments: '--no-check-bioc-help' 
        
      - name: Upload check results
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.config.os }}-results
          path: ${{ steps.build-install-check.outputs.check-dir }}
          
      - name: Upload check results
        if: ${{ failure() }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.config.os }}-${{ matrix.config.r }}-hdf5_config.log
          path: check/*.Rcheck/00_pkg_src/Rhdf5lib/src/hdf5/config.log
