# See https://ropensci.org/blog/2026/01/03/r-universe-workflows/
name: Test R-universe

on:
  workflow_dispatch:

jobs:
  build:
    name: R-universe testing
    uses: r-universe-org/workflows/.github/workflows/build.yml@v3
    with:
      universe: ${{ github.repository_owner }}